### ISSUE TITLE
Possible wrong lifetime used for returned text slices.

### ISSUE THREAD

**Issue by rustonaut** [RazrFalcon/roxmltree#11]
Many functions return text slices with a `'a` lifetime instead of the `'d` lifetime.

E.g. in `Node` there is `fn tag_name(&self) -> ExpandedName<'a>` but it probably should be
`fn tag_name(&self) -> ExpandedName<'d>`.

(The `ExpandedName` documentation also uses `'d` to imply it should be using the document
lifetime if I'm not wrong).

There are a number of other functions which are also affected, but I havent looked enough into the crate if some of them might actually need to use `'a`.

Possible candidates are:
- `default_namespace`
- `resolve_tag_name_prefix`
- `lookup_prefix`
- `lookup_namespace_uri`
- ...

There are also some functions which accept a `&'a str` (or similar) as input,
but should accept any kind of lifetime as they are only used to compare
with the tree (like e.g. `lookup_namespace_uri`).

Note that none of the fixes would be breaking changes as they only can
prolong the "duration" of the returned lifetime (as far as you can speak
of duration).

Lastly I think:
```
fn has_attribute<N>(&self, name: N) -> bool where
    N: Into<ExpandedName<'a>>,
```

should be more like

```
fn has_attribute<N>(&self, name: N) -> bool where
    N: PartialEq<ExpandedName<'a>>>,
```

which would be a braking change but far more flexible,
for one it would work for any lifetime of passed in `ExpandedName`
even if shorter then `'a`, additionally it works better with custom
types, again independent of the lifetime as long as eq is
implemented with a wildcard `'a`.

**Comment by RazrFalcon** [comment]
I've tried changing lifetimes and got a bunch of errors. Can you send a pull request?

I'm not sure that `PartialEq` will work. This methods accepts `ExpandedName`, `&str` and `(&str, &str)`.

**Comment by tmiasko** [comment]
Last time I looked into extending lifetimes, the major impediment to just using
text content lifetime everywhere have been URIs. If `'d` is lifetime of text
content, and `'a` is lifetime of `Document` struct, then whenever there is a
reference to an URI, you can't return lifetime longer than `'a`, because URIs
are stored by value inside `Document`.

So you could extend `resolve_tag_name_prefix`, `lookup_prefix`, but not
`tag_name`, `default_namespace`, or `lookup_namespace_uri`.

**Comment by RazrFalcon** [comment]
Can you make a pull request with those changes?

**Comment by rustonaut** [comment]
Uhm, I pushed back answering as a didn't know if I would have time for a PR. By now it's kinda obvious that I currently don't have the time. I might come back to this when I have a bit more time.

**Comment by TimDiekmann** [comment]
Can this be reopend? This is not solved yet and it's impossible to get string slices out of this parser without cloning, when values should outlive `Document`.

**Comment by RazrFalcon** [comment]
@TimDiekmann can you provide an example?

**Comment by TimDiekmann** [comment]
```rust
let attribute = {
    let doc = roxmltree::Document::parse("<e a='b'/>").unwrap();
    doc.root_element().attribute("a").unwrap()
};
assert_eq!(attribute, "b");
```

```
    let attribute = {
        let doc = roxmltree::Document::parse("<e a='b'/>").unwrap();
        doc.root_element().attribute("a").unwrap()
    };
    assert_eq!(attribute, "b");
```

**Comment by RazrFalcon** [comment]
This is an expected behavior. Input should outlive the `Document`. I guess that in this exact case lifetime should fallback to `'static`, but I have no idea why it doesn't work.

**Comment by TimDiekmann** [comment]
Why is this an expected behavior? The document takes a `&'input str`. `xmlparser` only works with slices, thus every output of `xmlparser` has still the same lifetime. In the provided example, the input is `&'static str` and `attribute` should have a static lifetime, too. 

I know, that an attribute **may** have to allocate when normalizing, but in most cases, you don't have to. Internally, you are using `Cow<'input, str>`. We may have a method returning `&Cow<'input, str>`.

Another thing: Node stores the `Uri` as `String`, why not `Cow<'input, str>` as well? However, it's not possible to return the uri as `&Cow<'input, str>`, as `ExpandedNameOwned`s design is flawed.

**Comment by RazrFalcon** [comment]
>Why is this an expected behavior?

Because this is how it was designed.

>We may have a method returning &Cow<'input, str>.

It's ugly. I don't wan't to expose any internal structures into a public API. User should only interact with `&str`.

>Node stores the Uri as String, why not Cow<'input, str> as well?

Less fighting with lifetimes. And it doesn't affect the performance anyway, last time I've check.

>as ExpandedNameOwneds design is flawed

You're free to create a pull request.
